/** generated from lipsum.com */
export const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur vestibulum sapien nec imperdiet. Sed lacus risus, aliquam sit amet nisi a, iaculis mollis dui. Nam fermentum orci ullamcorper ante tristique, at tincidunt leo fermentum. Nulla facilisi. Sed ullamcorper vitae mauris in tempus. Maecenas aliquam enim tempus orci blandit, vel suscipit erat pretium. Suspendisse quis faucibus orci. Fusce auctor, dolor et tempor suscipit, quam metus finibus enim, et mattis urna eros eu nibh. Praesent id lacinia nulla. Sed eget elit porta, dapibus dolor ut, mollis turpis. Aliquam vitae sapien sollicitudin, luctus eros non, fringilla velit. Praesent eu magna convallis, pretium dui id, efficitur est. In leo metus, sagittis et interdum a, condimentum sed massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Integer feugiat, enim quis sagittis semper, est neque suscipit diam, nec maximus tellus quam sit amet nulla. Vestibulum varius quis libero non tempus. Proin vitae felis sed mauris eleifend luctus non a velit. Fusce scelerisque justo vel nibh laoreet feugiat. Sed nec nunc sit amet lectus accumsan tincidunt et nec tellus. Nam tempor metus ac pretium eleifend. Sed malesuada sapien est, eget vestibulum lectus tincidunt a. Integer vel pulvinar mauris. In vitae tellus quis purus fermentum ullamcorper.

Aenean at nibh ac justo egestas sodales. Nullam varius eget dui nec consectetur. Donec dapibus dictum convallis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In eget lorem interdum, ullamcorper neque a, ornare lacus. Donec non iaculis urna, ac tincidunt libero. Ut urna ex, commodo sed aliquam at, sollicitudin pharetra magna. Fusce lobortis feugiat erat. Suspendisse potenti. Donec sagittis, nibh eget vehicula porta, quam quam rhoncus nibh, sed hendrerit lacus nisl eu nulla. Vivamus vel condimentum nulla. Sed sollicitudin felis urna, ut pellentesque est tincidunt nec.

Integer suscipit elit diam, in tristique libero tempor quis. Fusce ac augue lacus. Aliquam vestibulum tellus lacus, quis aliquet dui cursus a. Mauris condimentum lobortis arcu at tristique. Vivamus libero velit, egestas ac justo at, varius venenatis erat. Sed aliquam convallis erat, interdum semper ligula sodales quis. Donec quis maximus ex, vel eleifend tellus. Cras rhoncus ornare efficitur. Phasellus sodales, nibh eu aliquet vulputate, risus eros sagittis purus, nec tincidunt mauris orci ut neque.

Duis commodo quam nec metus commodo facilisis. Phasellus eget nunc felis. Mauris semper malesuada eleifend. Fusce quis diam massa. Sed varius pretium cursus. Nulla fringilla ligula at ante dictum, sit amet mattis nisl fermentum. Pellentesque tempor dictum leo sollicitudin rhoncus. Nam vitae volutpat diam. Morbi mollis tempus ante, nec euismod tortor porttitor ac. Etiam in metus fringilla, consectetur eros ut, varius ipsum. In dictum, eros ac rhoncus aliquam, est lacus interdum quam, et consequat lacus sapien in mi. Sed aliquam urna quam.`;
